# Generated by Django 3.1.1 on 2020-09-04 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_times', models.CharField(choices=[('morning', 'morning'), ('midmorning', 'midmorning'), ('afternoon', 'afternoon')], max_length=10)),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('room_capacity', models.IntegerField()),
                ('speaker', models.CharField(max_length=100)),
                ('event_image', models.ImageField(blank=True, help_text='Event Thumbnail', null=True, upload_to='eventpics/')),
                ('venue_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('accept_terms', models.BooleanField(default=False)),
                ('registered_events', models.ManyToManyField(blank=True, to='events.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
