# Generated by Django 3.1.1 on 2020-09-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
